### ISSUE TITLE
Non-secure output differs from secure

### ISSUE THREAD

**Issue by prichey** [pixijs/customize#17]
Somehow I ended up on the [non-secure](http://pixijs.io/customize/) version of the customize page and was confused when the output didn't match what I expected. I posted a separate issue (https://github.com/pixijs/customize/issues/16) about this thinking that the minimal setup was wrong but it turns out this isn't an issue for the https page. Seems to me like the site should force https anyway but regardless it seems like an issue that the output would differ based on the protocol.

**Comment by bigtimebuddy** [comment]
I enabled forcing HTTPS. I’ll check into why HTTP was choking. What browser are you using @prichey?

**Comment by prichey** [comment]
I use Firefox. Can confirm I'm seeing the HTTPS forcing now
