### ISSUE TITLE
Documents/Tips  Request

### ISSUE THREAD

**Issue by HusakYurii** [pixijs/customize#25]
Are there any docs describing what each dependency is responsible for (in context of PIXI.js customize tool)? It should give more clear understanding of what to include to compose a build for your needs.

For ex:
```javascript
 // To make very base PIXI build it must include these dependencies which are ticked by default
 '@pixi/constants';
 '@pixi/math';
 '@pixi/runner';
 '@pixi/settings';
 '@pixi/ticker';
 '@pixi/utils';
 '@pixi/core';
  // and the Application to run PIXI app (which has stage, view, ticker etc)
 '@pixi/app'

// If you are going to use  Containers and be able to calculate its Bounds, you have to include
'@pixi/display'
```

etc...

If you do not have time, I can help with the base tips and examples for it

**Comment by ivanpopelyshev** [comment]
Here it is: https://github.com/pixijs/customize/blob/main/src/CodeUtils.ts

No, but people requested it several times already. Its shame that no one actually wants to do that after they expressed it :)

You can search related issues in https://github.com/pixijs/pixi.js/, I remember there were a few.

**Comment by HusakYurii** [comment]
@ivanpopelyshev thanks for the quick response!
I am not that good at understanding of those dependencies and what each is intended for (used pixi.js bundle with all in), but I will make a doc with examples and tips. After that will add a link here, so you can take a look

**Comment by HusakYurii** [comment]
@ivanpopelyshev hey!
I started working on some examples, the draft can be found here:
https://docs.google.com/document/d/1hm9SXczkrWH4mbHFed0xfn4CHRFbPMy0CZeDseyhYaU/edit?usp=sharing

If you have any comments, you are very welcome to leave them in the draft

**Comment by MicoLi2019** [comment]
Do you have any plans to launch Chinese documents and Chinese api documents?

**Comment by HusakYurii** [comment]
Not sure if they still support the PixiJS Customize, but the example was finished. You can follow the link I added before, but it was written in English.

If I understood correctly, @ivanpopelyshev is not in the PIXI team anymore and doesn't contribute anymore (((

**Comment by ivanpopelyshev** [comment]
@HusakYurii there's a chance i'll return. I'm currently still not rested enough )

**Comment by HusakYurii** [comment]
I have moved the article to this repository [pixi-customize-tips](https://github.com/HusakYurii/pixi-customize-tips)
