### ISSUE TITLE
Feature Request: Typescript support

### ISSUE THREAD

**Issue by scythianfuego** [pixijs/customize#8]
The thing is @pixi/* modules don't have any type declarations (as everything is in pixi.js module),
so typescript has no type information when importing directly.

It will compile, but systems like webpack at-loader treat this as fatal generating 
`TS2339: Property does not exist on type ...`

**Comment by bigtimebuddy** [comment]
Yeah this is more an issue with pixijs not having typings yet. We are working on this support by converting to TypeScript. 

As a workaround, you can see what I did with pixi-sound by manually creating typings:

https://github.com/pixijs/pixi-sound/tree/master/typings

**Comment by bigtimebuddy** [comment]
Typings are available for all packages now. Closing
